//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Input Action Maps.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActionMaps: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActionMaps()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Action Maps"",
    ""maps"": [
        {
            ""name"": ""Cursor"",
            ""id"": ""7880bac8-8a3a-4364-b0fa-529350bb487f"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""eface59d-687e-40cd-8311-aaa573da1ff2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Unselect"",
                    ""type"": ""Button"",
                    ""id"": ""93e3c881-17d7-4cf7-90aa-28f745086074"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drag"",
                    ""type"": ""Button"",
                    ""id"": ""e1836828-d567-459b-8efa-c78e670864c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""ec1b7488-00cd-41ab-8e9f-adb0bac4f6fa"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d81947cf-e338-4a45-9b05-7dff6448b093"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daa5675d-23bb-4949-8583-778cfd7b8aed"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""483c31a5-44ab-4d8a-97c6-4920dc514524"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6644196-d230-4a95-b8fc-cde295f6e187"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Camera"",
            ""id"": ""b0469837-5996-4bc5-927a-eef931d7c741"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""6686db07-6857-4074-a83b-91094d1299f0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate Left"",
                    ""type"": ""Button"",
                    ""id"": ""31692e2d-b630-4fb4-be84-d6beba9f5fdb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotate Right"",
                    ""type"": ""Button"",
                    ""id"": ""9d8c60ca-09c8-4864-b597-1006982289b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset Rotation"",
                    ""type"": ""Button"",
                    ""id"": ""a3f8a95d-b71f-4abd-b39c-12c5bbb5cf09"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tilt Down"",
                    ""type"": ""Button"",
                    ""id"": ""fbcbdc84-193e-4020-92f6-acb001f44343"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tilt Up"",
                    ""type"": ""Button"",
                    ""id"": ""eb8f9f8e-4f16-49a2-a915-a726ee6149cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset Tilt"",
                    ""type"": ""Button"",
                    ""id"": ""ba283145-2906-482a-be2d-6f70e670d9dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""ee230b81-6477-45ca-ba0a-ef06450e420e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a85f4756-d5e4-4e6a-8407-88aa9daa6905"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e57e08d4-6c90-44cc-9c7c-b0e2851d6f86"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""95e381b3-4c54-44bb-a4b2-24d16c169dcf"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6640fc64-702b-4856-bc03-d5e2175577a0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""195e94ea-1410-45d8-b88b-6f56ad7cccb0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Rotate Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""071560c3-0c82-4cb5-b3c4-e8da0c716a25"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Rotate Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0060b9b-310a-4d2a-89d7-75bc134c7175"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Reset Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""309983f7-7715-4e48-b63a-b3a2f085dbfe"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Tilt Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""979361f8-4b71-4bfc-995b-d78678e49fcc"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Tilt Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8e1570f-4662-4af2-a1b2-a70463016139"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset Tilt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Friend"",
            ""id"": ""9d1088ea-579a-4f4b-9ae3-be8edc839519"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""203d6205-9a39-4e31-9b88-927440bd736d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Multi Select"",
                    ""type"": ""Button"",
                    ""id"": ""207d0eb3-3da7-4b24-af1e-b2ed29f0ea1a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a6b54097-6e3d-4c4a-bd6b-dcff0adad264"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard "",
                    ""action"": ""Multi Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e1221c6-f70e-4e9f-a455-ed6bd3007877"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard "",
            ""bindingGroup"": ""Keyboard "",
            ""devices"": []
        },
        {
            ""name"": ""Mouse"",
            ""bindingGroup"": ""Mouse"",
            ""devices"": []
        }
    ]
}");
        // Cursor
        m_Cursor = asset.FindActionMap("Cursor", throwIfNotFound: true);
        m_Cursor_Select = m_Cursor.FindAction("Select", throwIfNotFound: true);
        m_Cursor_Unselect = m_Cursor.FindAction("Unselect", throwIfNotFound: true);
        m_Cursor_Drag = m_Cursor.FindAction("Drag", throwIfNotFound: true);
        m_Cursor_Scroll = m_Cursor.FindAction("Scroll", throwIfNotFound: true);
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Movement = m_Camera.FindAction("Movement", throwIfNotFound: true);
        m_Camera_RotateLeft = m_Camera.FindAction("Rotate Left", throwIfNotFound: true);
        m_Camera_RotateRight = m_Camera.FindAction("Rotate Right", throwIfNotFound: true);
        m_Camera_ResetRotation = m_Camera.FindAction("Reset Rotation", throwIfNotFound: true);
        m_Camera_TiltDown = m_Camera.FindAction("Tilt Down", throwIfNotFound: true);
        m_Camera_TiltUp = m_Camera.FindAction("Tilt Up", throwIfNotFound: true);
        m_Camera_ResetTilt = m_Camera.FindAction("Reset Tilt", throwIfNotFound: true);
        // Friend
        m_Friend = asset.FindActionMap("Friend", throwIfNotFound: true);
        m_Friend_Select = m_Friend.FindAction("Select", throwIfNotFound: true);
        m_Friend_MultiSelect = m_Friend.FindAction("Multi Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Cursor
    private readonly InputActionMap m_Cursor;
    private List<ICursorActions> m_CursorActionsCallbackInterfaces = new List<ICursorActions>();
    private readonly InputAction m_Cursor_Select;
    private readonly InputAction m_Cursor_Unselect;
    private readonly InputAction m_Cursor_Drag;
    private readonly InputAction m_Cursor_Scroll;
    public struct CursorActions
    {
        private @InputActionMaps m_Wrapper;
        public CursorActions(@InputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Cursor_Select;
        public InputAction @Unselect => m_Wrapper.m_Cursor_Unselect;
        public InputAction @Drag => m_Wrapper.m_Cursor_Drag;
        public InputAction @Scroll => m_Wrapper.m_Cursor_Scroll;
        public InputActionMap Get() { return m_Wrapper.m_Cursor; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CursorActions set) { return set.Get(); }
        public void AddCallbacks(ICursorActions instance)
        {
            if (instance == null || m_Wrapper.m_CursorActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CursorActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Unselect.started += instance.OnUnselect;
            @Unselect.performed += instance.OnUnselect;
            @Unselect.canceled += instance.OnUnselect;
            @Drag.started += instance.OnDrag;
            @Drag.performed += instance.OnDrag;
            @Drag.canceled += instance.OnDrag;
            @Scroll.started += instance.OnScroll;
            @Scroll.performed += instance.OnScroll;
            @Scroll.canceled += instance.OnScroll;
        }

        private void UnregisterCallbacks(ICursorActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Unselect.started -= instance.OnUnselect;
            @Unselect.performed -= instance.OnUnselect;
            @Unselect.canceled -= instance.OnUnselect;
            @Drag.started -= instance.OnDrag;
            @Drag.performed -= instance.OnDrag;
            @Drag.canceled -= instance.OnDrag;
            @Scroll.started -= instance.OnScroll;
            @Scroll.performed -= instance.OnScroll;
            @Scroll.canceled -= instance.OnScroll;
        }

        public void RemoveCallbacks(ICursorActions instance)
        {
            if (m_Wrapper.m_CursorActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICursorActions instance)
        {
            foreach (var item in m_Wrapper.m_CursorActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CursorActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CursorActions @Cursor => new CursorActions(this);

    // Camera
    private readonly InputActionMap m_Camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_Camera_Movement;
    private readonly InputAction m_Camera_RotateLeft;
    private readonly InputAction m_Camera_RotateRight;
    private readonly InputAction m_Camera_ResetRotation;
    private readonly InputAction m_Camera_TiltDown;
    private readonly InputAction m_Camera_TiltUp;
    private readonly InputAction m_Camera_ResetTilt;
    public struct CameraActions
    {
        private @InputActionMaps m_Wrapper;
        public CameraActions(@InputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Camera_Movement;
        public InputAction @RotateLeft => m_Wrapper.m_Camera_RotateLeft;
        public InputAction @RotateRight => m_Wrapper.m_Camera_RotateRight;
        public InputAction @ResetRotation => m_Wrapper.m_Camera_ResetRotation;
        public InputAction @TiltDown => m_Wrapper.m_Camera_TiltDown;
        public InputAction @TiltUp => m_Wrapper.m_Camera_TiltUp;
        public InputAction @ResetTilt => m_Wrapper.m_Camera_ResetTilt;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @RotateLeft.started += instance.OnRotateLeft;
            @RotateLeft.performed += instance.OnRotateLeft;
            @RotateLeft.canceled += instance.OnRotateLeft;
            @RotateRight.started += instance.OnRotateRight;
            @RotateRight.performed += instance.OnRotateRight;
            @RotateRight.canceled += instance.OnRotateRight;
            @ResetRotation.started += instance.OnResetRotation;
            @ResetRotation.performed += instance.OnResetRotation;
            @ResetRotation.canceled += instance.OnResetRotation;
            @TiltDown.started += instance.OnTiltDown;
            @TiltDown.performed += instance.OnTiltDown;
            @TiltDown.canceled += instance.OnTiltDown;
            @TiltUp.started += instance.OnTiltUp;
            @TiltUp.performed += instance.OnTiltUp;
            @TiltUp.canceled += instance.OnTiltUp;
            @ResetTilt.started += instance.OnResetTilt;
            @ResetTilt.performed += instance.OnResetTilt;
            @ResetTilt.canceled += instance.OnResetTilt;
        }

        private void UnregisterCallbacks(ICameraActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @RotateLeft.started -= instance.OnRotateLeft;
            @RotateLeft.performed -= instance.OnRotateLeft;
            @RotateLeft.canceled -= instance.OnRotateLeft;
            @RotateRight.started -= instance.OnRotateRight;
            @RotateRight.performed -= instance.OnRotateRight;
            @RotateRight.canceled -= instance.OnRotateRight;
            @ResetRotation.started -= instance.OnResetRotation;
            @ResetRotation.performed -= instance.OnResetRotation;
            @ResetRotation.canceled -= instance.OnResetRotation;
            @TiltDown.started -= instance.OnTiltDown;
            @TiltDown.performed -= instance.OnTiltDown;
            @TiltDown.canceled -= instance.OnTiltDown;
            @TiltUp.started -= instance.OnTiltUp;
            @TiltUp.performed -= instance.OnTiltUp;
            @TiltUp.canceled -= instance.OnTiltUp;
            @ResetTilt.started -= instance.OnResetTilt;
            @ResetTilt.performed -= instance.OnResetTilt;
            @ResetTilt.canceled -= instance.OnResetTilt;
        }

        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // Friend
    private readonly InputActionMap m_Friend;
    private List<IFriendActions> m_FriendActionsCallbackInterfaces = new List<IFriendActions>();
    private readonly InputAction m_Friend_Select;
    private readonly InputAction m_Friend_MultiSelect;
    public struct FriendActions
    {
        private @InputActionMaps m_Wrapper;
        public FriendActions(@InputActionMaps wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_Friend_Select;
        public InputAction @MultiSelect => m_Wrapper.m_Friend_MultiSelect;
        public InputActionMap Get() { return m_Wrapper.m_Friend; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FriendActions set) { return set.Get(); }
        public void AddCallbacks(IFriendActions instance)
        {
            if (instance == null || m_Wrapper.m_FriendActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FriendActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @MultiSelect.started += instance.OnMultiSelect;
            @MultiSelect.performed += instance.OnMultiSelect;
            @MultiSelect.canceled += instance.OnMultiSelect;
        }

        private void UnregisterCallbacks(IFriendActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @MultiSelect.started -= instance.OnMultiSelect;
            @MultiSelect.performed -= instance.OnMultiSelect;
            @MultiSelect.canceled -= instance.OnMultiSelect;
        }

        public void RemoveCallbacks(IFriendActions instance)
        {
            if (m_Wrapper.m_FriendActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFriendActions instance)
        {
            foreach (var item in m_Wrapper.m_FriendActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FriendActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FriendActions @Friend => new FriendActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard ");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_MouseSchemeIndex = -1;
    public InputControlScheme MouseScheme
    {
        get
        {
            if (m_MouseSchemeIndex == -1) m_MouseSchemeIndex = asset.FindControlSchemeIndex("Mouse");
            return asset.controlSchemes[m_MouseSchemeIndex];
        }
    }
    public interface ICursorActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnUnselect(InputAction.CallbackContext context);
        void OnDrag(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
    }
    public interface ICameraActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnRotateLeft(InputAction.CallbackContext context);
        void OnRotateRight(InputAction.CallbackContext context);
        void OnResetRotation(InputAction.CallbackContext context);
        void OnTiltDown(InputAction.CallbackContext context);
        void OnTiltUp(InputAction.CallbackContext context);
        void OnResetTilt(InputAction.CallbackContext context);
    }
    public interface IFriendActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnMultiSelect(InputAction.CallbackContext context);
    }
}
